const cryptoData = [
  {
    id: 1,
    title: "WBTC-WETH",
    change: "0.97",
    color1: "#F19241",
    color2: "#ED4694",
    img1: "https://test.joinclamp.com/tokens/WBTC.svg",
    img2: "https://test.joinclamp.com/tokens/WETH.svg",
  },
  {
    id: 2,
    title: "USDC-WETH",
    change: "1.23",
    color1: "#2775CA",
    color2: "#ED4694",
    img1: "https://test.joinclamp.com/tokens/USDC.svg",
    img2: "https://test.joinclamp.com/tokens/WETH.svg",
  },
  {
    id: 3,
    title: "USDC-WBTC",
    change: "0.56",
    color1: "#2775CA",
    color2: "#F19241",
    img1: "https://test.joinclamp.com/tokens/USDC.svg",
    img2: "https://test.joinclamp.com/tokens/WBTC.svg",
  },
  {
    id: 4,
    title: "WETH-WMATIC",
    change: "0.97",
    color1: "#ED4694",
    color2: "#8B5CF6",
    img1: "https://test.joinclamp.com/tokens/WETH.svg",
    img2: "https://test.joinclamp.com/tokens/WMATIC.svg",
  },
  {
    id: 5,
    title: "USDC-WMATIC",
    change: "1.23",
    color1: "#2775CA",
    color2: "#8B5CF6",
    img1: "https://test.joinclamp.com/tokens/USDC.svg",
    img2: "https://test.joinclamp.com/tokens/WMATIC.svg",
  },
  {
    id: 6,
    title: "WBTC-WETH-USDC",
    change: "0.97",
    color1: "#F19241",
    color2: "#ED4694",
    color3: "#8B5CF6",
    img1: "https://test.joinclamp.com/tokens/WBTC.svg",
    img2: "https://test.joinclamp.com/tokens/WETH.svg",
    img3: "https://test.joinclamp.com/tokens/USDC.svg",
  },
  {
    id: 7,
    title: "WBTC-WETH-WMATIC",
    change: "1.23",
    color1: "#FACA15",
    color2: "#2775CA",
    color3: "#F19241",
    img1: "https://test.joinclamp.com/tokens/WBTC.svg",
    img2: "https://test.joinclamp.com/tokens/WETH.svg",
    img3: "https://test.joinclamp.com/tokens/WMATIC.svg",
  },
  {
    id: 8,
    title: "DAI-USDC-WBTC",
    change: "0.56",
    color1: "#FACA15",
    color2: "#2775CA",
    color3: "#F19241",
    img1: "https://test.joinclamp.com/tokens/DAI.svg",
    img2: "https://test.joinclamp.com/tokens/USDC.svg",
    img3: "https://test.joinclamp.com/tokens/WBTC.svg",
  },
  {
    id: 9,
    title: "DAI-WETH-WBTC",
    change: "0.56",
    color1: "#FACA15",
    color2: "#2775CA",
    color3: "#F19241",
    img1: "https://test.joinclamp.com/tokens/DAI.svg",
    img2: "https://test.joinclamp.com/tokens/WETH.svg",
    img3: "https://test.joinclamp.com/tokens/WBTC.svg",
  },
];

export default cryptoData;
